# Generated by Django 4.0.6 on 2022-07-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='animals',
            field=models.ManyToManyField(related_name='characteristics', to='animals.animal'),
        ),
    ]
