# Generated by Django 4.0.6 on 2022-07-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0002_characteristic_animals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='animals',
        ),
    ]
