# Generated by Django 4.0.6 on 2022-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_remove_characteristic_animals'),
        ('animals', '0002_animal_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='characteristics',
            field=models.ManyToManyField(related_name='animals', to='characteristics.characteristic'),
        ),
    ]
