# Generated by Django 4.0.6 on 2022-07-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_group_animals'),
        ('animals', '0004_remove_animal_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='groups.group'),
            preserve_default=False,
        ),
    ]
