# Generated by Django 4.0.6 on 2022-07-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_remove_animal_group'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='animals',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='gruop', to='animals.animal'),
            preserve_default=False,
        ),
    ]
