# Generated by Django 4.0.6 on 2022-07-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_animals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='animals',
        ),
    ]
